require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.diagnostics")
require("config.pack")
require("plugins")
require("config.lsp")
require("core.terminal_manager").setup()
